version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight_lbs
        tests:
          - positive_values
      - name: weight_kg
        tests:
          - positive_values
  - name: stg_users
  - name: stg_addresses
  - name: stg_events
  - name: stg_order_items
  - name: stg_orders
  - name: stg_products
  - name: stg_promos