version: 2

models:
  - name: stg_users
    description: Contains demographic information about each user.
    columns:
      - name: user_guid
        tests:
          - not_null
          - unique
  - name: stg_addresses
    description: User addresses. Referenced by Orders for delivery address.
    columns:
      - name: address_id
        tests:
          - not_null
          - unique
  - name: stg_events
    description: App events for key user interactions
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: session_id
        tests:
          - not_null
  - name: stg_order_items
    description: Connecting table for order line-items, linking Products -> Orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
  - name: stg_orders
    description: Customer orders. References- Users, Addresses, Orders, Promos.
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_guid
        tests:
          - not_null
      - name: order_cost
        tests:
          - positive_values
      - name: shipping_cost
        tests:
          - positive_values
  #test-todo: created_at is before delviered_at, estimated_delivered_at
  - name: stg_products
    description: Product SKU data - name, price, volume
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: inventory
        tests:
          - positive_values
      - name: price
        tests:
          - positive_values   
  - name: stg_promos
    description: Discount code amounts and status - 'inactive', or 'active'
    columns:
      - name: promo_id
        tests: 
          - not_null
          - unique
      - name: discount
        tests:
          - positive_values